site_name: LDIMBenchmark
theme:
  name: material

watch:
 - docs/
 - src/

nav:
- Index: index.md
- Design: design.md
- Guides:
  - Docker: user-guides/docker.md
- Roadmap: roadmap.md
- Code Reference: reference/

plugins:
  - search
  - gen-files:
      scripts:
      - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - autorefs
  - mkdocstrings

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.snippets